@startuml

'skinparam svgDimensionStyle false

title Abstract Model

package "Basics (directly mentioned as requirements)" {

class "Property" as prop

class "Object" as obj

class "Data Element" as de

obj "1" *-- "1..*" de
obj *-- "0..*" prop

class "Data Type" as dt
class "Format" as format

de -- dt : has >
de -- format : uses >


class "Code" as code

de -- code : uses >

class "Procedure" as proc

proc -left- obj : perform on >

}

package "Supporting (derived information)" {

class "Relationship" as rel
Note right of rel
to link artefacts
together
end Note

class "Codesystem" as cs
class "Value Set" as vs
Note right of vs
normally only 
a subset from 
the codesystem 
is used
end Note

vs -left- cs : subset of >

rel -[hidden]down- cs

}

cs *-- "0..*" code : belongs to <
vs *-- "0..*" code : contained in <


@enduml