@startuml

skinparam svgDimensionStyle false

Title "WP Cooperation (from WP2 T2.2 perspective)"

collections "Legislation" as l
collections "[[index.html Standards]]" as s

actor "WP1" as wp1
collections "WP1\nDeliverable: \nRequirements" as r
actor "WP2" as wp2
actor "T2.2" as t22
participant "[[CodeSystem-DigitalLabelElement.html DLE\nLibary]]" as s2
collections "WP2\nDeliverable:\n[[informationmodel.html Information\n    Model]]" as s3
collections "WP2\nDeliverable:\n Model\n Profiles" as s4
actor "WP3" as wp3
actor "WP4" as wp4
participant "[[glossary.html Glossary\n     of\n  Terms]]" as g
collections "Other \nDeliverables" as r2

l -> wp1 : import
activate wp1
s -> wp1 : import
wp1 -> r
wp1 -> g
deactivate wp1

r -> wp2
activate wp2
wp2 -> t22 : start work
activate t22
r -> t22 : import definitions
t22 -> t22: transform/\nmap\ndefinitions
activate t22
t22 -> s2 : crfeate/update library
deactivate t22

t22 -> t22 : create model
activate t22
s2 -> t22 : consider artefacts
t22 -> s3 : update
deactivate t22
deactivate t22
wp2 -> wp2 : verify the model ??
wp2 -> wp2 : profile the model ??
activate wp2
wp2 -> s3 : update model
wp2 -> s4 : improve profile set
deactivate wp2

wp2 -> g

deactivate wp2
r -> wp3
activate wp3
wp3 -> g
wp3 -> r2
deactivate wp3
r -> wp4
activate wp4
wp4 -> g
wp4 -> r2
deactivate wp4

legend
WP x: activities in work package
DLE: "Digital Label Elements"
Artefacts: intermediary list of items needed to create to know for the information model
[[glossary.html Glossary of Terms]]: all WPs should contribute to this list
end legend

@enduml