@startmindmap

skinparam svgDimensionStyle false

title MindMap with all details assembled so far

+ [[StructureDefinition-MindMap.html mindMap]]

-- Risk Management
---_ Hazard
---_ Risk Mitigation
-- Symbol
---_ [[CodeSystem-SafetySigns7010.html icon]]
---_ [[CodeSystem-SafetySign7010Category.html type]]
---_ explanation
---_ where used
-- Documentation\n(=sum of documents)
-- Document
---_ electronic/printed instruction for use (IFU)
---_ manual
---_ technical description
---_ website
--[#bfb] Process
---_ manufacturing
---_ documenting
---_ testing
---_ labeling
---_ handling
----_ prepare for use
-----_ sterilize
----_ prepare for storage
----_ before use
-----_ heating/cooling
----_ during use
----_ after use
-----_ cooling
------_ freezing
----_ for reuse
----_ dispose
-----_ sterilize
----_ storing
--[#ffb] Codes
---_ Country
---_ Language
---_ Symbol
----_ ISO 7000
----_ ISO 7010
---_ other..
--[#ffb] Formats
---_ Date/Time
---_ Numbers


++ Label
+++_ Producer/Manufacturer
++++_ Identification
++++_ Name
++++_ Address
++++_ Telecom
+++_ Product Identification
+++_ use of symbols
++ (medical) device (aka product)
++ Product Information
+++_ name + description
+++_ [[CodeSystem-DeviceClass.html class]]: I, II, IIa, IIb, III
+++_ [[CodeSystem-DeviceType.html type]]/family
+++_ property
++++_ single use/reusable
++++_ implantable
++++_ disposable
++++_ sterilizable
++++_ sharp (edges)
++++_ nano technology
++++_ other...
+++_ production date
+++_ expiry date
+++_ Safety-related warnings or restrictions
++ Package
+++_ amount of contained devices
++ Container
+++_ (as part of package)
++ Specific (produced) Device
+++_ Identification
++++_ Serial Number
++++_ Lot Number
++++_ Batch Number
+++_ (detachable) component
+++_ other....
++ Accessory
+++_ identification
+++_ description
++ Spare Part
+++_ identification
+++_ description
++ Information
+++_ on Website
+++_ on Package/Box
+++_ on Container (Blister)
+++_ on Device
++ Comment

@endmindmap