@startuml

'skinparam svgDimensionStyle false

Title "Legislation vs. Standard"

class "Legislation" as l1
class "Realization" as l2

l1 <-- l2 : compliant

class "Standard" as s1
class "Realization" as s2

s1 <-- s2 : conformant

@enduml