@startuml

'skinparam svgDimensionStyle false

Title "Document (Profile) vs. Process (Implementation)"

class "Standard" as s1
class "Profile \n(from standard)" as s2
class "Implementation \n(Software according to profile)" as s3

s1 <-- s2 : conformant
s2 <-- s3 : compliant

@enduml